### PR TITLE
Created rajdeepchakraborty-rc.md

### PR DESCRIPTION
**Pull request by rajdeepchakraborty-rc**
Added my unmerged PR:

- https://github.com/AlgoGenesis/C/pull/1847 [**level1**]

### CODE REVIEW

**Comment by rajdeepchakraborty-rc** [comment]
@aslams2020 Please review the PR.

**Comment by rajdeepchakraborty-rc** [comment]
This is not a Postman/Web3 PR.

**Review by aslams2020 — COMMENTED** [review]
documentations

**Comment by rajdeepchakraborty-rc** [comment]
> documentations

@aslams2020 What does that mean?

**Comment by aslams2020** [comment]
means non-technical contributions ..which comes in guidelines as atmax level1

**Comment by rajdeepchakraborty-rc** [comment]
> means non-technical contributions ..which comes in guidelines as atmax level1

This repository is about contributing C Algorithms and Programs only. So there is only a documentation-based contribution for this repository. Well fine if you identify it that way. I just wanted to clear it out. 
Thanks for reviewing.

**Pull request merged**
