### PR TITLE
Create Nishant.md

### PR DESCRIPTION
**Pull request by nishant4500**
@aslams2020 please look into this

### CODE REVIEW

**Comment by nishant4500** [comment]
@AKSHITHA-CHILUKA?

**Review by AKSHITHA-CHILUKA — APPROVED** [review]

**Comment by nishant4500** [comment]
@AKSHITHA-CHILUKA there is two pr!!!!!

**Comment by AKSHITHA-CHILUKA** [comment]
yeah i have seen the work its not worth of level 1  also so minimal changes but to encourage you i have given level1

**Comment by nishant4500** [comment]
thank you for the help!!

**Pull request merged**
