### PR TITLE
My Unmerged PR , Added Hemraj-7.md file

### PR DESCRIPTION
**Pull request by Hemraj-7**
## Please Checkout my valid unmerged PR
@MastanSayyad 
@sanjay-kv

### CODE REVIEW

**Comment by AKSHITHA-CHILUKA** [comment]
https://github.com/aslams2020/Stark-Tech-Portfolio/pull/416 it is still under review so please wait 


ttps://github.com/ayush-that/FinVeda/pull/3173 for this change no level will be assigned 
image

https://github.com/Open-Code-Crafters/FitFlex/pull/464 same here also for this change no level will be assigned 
image

https://github.com/himeshparashar/Social-Morph/pull/188 for this change no level will be assigned
image

https://github.com/swaraj-das/Collect-your-GamingTools/pull/742 no level will be given 
screencapture-github-swaraj-das-Collect-your-GamingTools-pull-742-files-2024-11-10-09_51_44

https://github.com/Anjaliavv51/Retro/pull/334 
screencapture-github-Anjaliavv51-Retro-pull-334-files-2024-11-10-09_53_50

**Comment by AKSHITHA-CHILUKA** [comment]
I can just give you level 1 just to encourage you , you have to concentrate on how to solve the issue no for points work more on the code and the changes you have mentioned

**Comment by Hemraj-7** [comment]
@AKSHITHA-CHILUKA 

Do you know how important even a single line of code is?

This is the code for Tailwind CSS. Just one line of code or a single class ruins the structure of the entire website.

**Comment by AKSHITHA-CHILUKA** [comment]
I know @Hemraj-7 as of now I can provide you only level 1

**Comment by Hemraj-7** [comment]
This is not fair with me.

Check this PR @sanjay-kv and @MastanSayyad

**Review by MastanSayyad — COMMENTED** [review]
@Hemraj-7 Reviewed all your PRs merged and addressed the issues 

`Anjaliavv51/Retro/pull/334` points for this PR has been given on this PR

**Comment by MastanSayyad** [comment]
> This is not fair with me.
> 
> Check this PR @sanjay-kv and @MastanSayyad

Kindly speak politely with the member of a core team, changes are indeed great but simple value adjustment is not called as open source, I have merged all your PRs and one PR will be review by the PA.

**Comment by Hemraj-7** [comment]
Hey! Any one can tell me what about my this unmerged PR - https://github.com/Trisha-tech/OnlineBookSales/pull/660

Please

**Comment by sanjay-kv** [comment]
@MastanSayyad already marked as resolved, which means the issue is solved @Hemraj-7

**Comment by MastanSayyad** [comment]
@sanjay-kv yes i merged and added labels to respective given PRs as i had access to them, however for one i didnt akshita labeled level 1 so scores are balanced

**Pull request merged**
