### PR TITLE
Create meetpidev.md

### PR DESCRIPTION
**Pull request by Meetpidev**
Please reviw PR

### CODE REVIEW

**Comment by Meetpidev** [comment]
@AKSHITHA-CHILUKA Please revviw PR

**Review by aslams2020 — COMMENTED** [review]
Already merged by akshita

**Comment by Meetpidev** [comment]
@aslams2020 This PR is not merged..

**Comment by Meetpidev** [comment]
@aslams2020 akshita gave point for other PR.. not for this.. this is still open.. you can check and it is level 3 PR..

**Comment by Meetpidev** [comment]
@aslams2020  ???

**Comment by AKSHITHA-CHILUKA** [comment]
Do not tag us every where and ask for points we will check every pr before 7 
dont tag us many times @Meetpidev

**Comment by aslams2020** [comment]
this PR has no changes, it cant be level1

**Comment by aslams2020** [comment]
adding a deployment link is not a contribution.

**Comment by Meetpidev** [comment]
> adding a deployment link is not a contribution.

IF NOT THEN WHY THEY ASSIGN ME ? AND AT LEVEL 3 ??  CONTRIBUTING ITS DOESN'T MEAN TO CONTRIBUTE SOME BIG.. JUST SMALL AMOUNT OF CHANGES IS ALSO CONTRIBUTION..

**Comment by AKSHITHA-CHILUKA** [comment]
This is not the way you talk to a Core team member @Meetpidev

**Comment by Meetpidev** [comment]
SORRY FOR THIS.. I  UNDERSTAND

**Pull request closed without merging**
