### PR TITLE
created VinayLodhi1712.md with unmerged PR's

### PR DESCRIPTION
**Pull request by VinayLodhi1712**
PR Not Merged under GSSOC Program-2024

1. Enyanjyoti - https://github.com/Vin205/Enyanjyoti/pull/543

2. Chanakya-niti - https://github.com/Avdhesh-Varshney/chanakya-niti/pull/370

3. Game-Player - https://github.com/divyansh-2005/GAME_PLAYER/pull/369

4. GDG Website - https://github.com/GDSC-RCCIIT/gdg-website/pull/473

5. Bitbox - https://github.com/Bitbox-Connect/Bitbox/pull/425 (This issue is of level 1 but after the admin told me to do this issue solved with the backend then its become an level 3 issue so add level 3 in it after seeing it.)

6. ##Closed with unmerged commits 
https://github.com/vishal02527/My-Strength-Shree-Krishna/pull/76

### CODE REVIEW

**Comment by MastanSayyad** [comment]
@VinayLodhi1712 create one more PR

**Comment by VinayLodhi1712** [comment]
> @VinayLodhi1712 create one more PR

for what..? 
with the same .md file..?

**Comment by MastanSayyad** [comment]
@VinayLodhi1712 yes, need to add level 2 that PR just refer this PR in it

**Comment by VinayLodhi1712** [comment]
> @VinayLodhi1712 yes, need to add level 2 that PR just refer this PR in it

yes sir but also i forgot to add one more so look into that also.

**Pull request merged**
