### PR TITLE
ADDED MY FILE

### PR DESCRIPTION
**Pull request by Meetpidev**
PLEASE REVIEW IT..

### CODE REVIEW

**Comment by Meetpidev** [comment]
@sanjay-kv Please Review IT..

**Comment by Meetpidev** [comment]
@sanjay-kv Requested To Review PR..

**Comment by Meetpidev** [comment]
@sanjay-kv Added issue number

**Comment by Meetpidev** [comment]
@sanjay-kv Requested to review again..

**Comment by AKSHITHA-CHILUKA** [comment]
https://github.com/Open-Code-Crafters/FitFlex/pull/450#issue-2642961432 as closed by PA no points 
https://github.com/recodehive/awesome-github-profiles/pull/1268#issue-2646886557 soon will be merged 
https://github.com/Soujanya2004/wanderlust-2024/pull/542#issue-2646420145  it will be added soon if not make a pr again for it after 4 pm
https://github.com/Soujanya2004/wanderlust-2024/pull/518#issue-2645873268 under review so labels will be added soon once you complete the changes requested 

https://github.com/sakeel-103/DFS-BFS-Graph-Travers/pull/610#issue-2646881332 complete the changes requested no labels will be given 


https://github.com/iamrahulmahato/master-web-development/pull/2385
image
no label for this kind of changes

**Comment by Meetpidev** [comment]
https://github.com/sakeel-103/DFS-BFS-Graph-Travers/pull/610#issue-2646881332  

@AKSHITHA-CHILUKA 
 IN THIS I MADE CHANGES IN FOOTER.. SEE IN THE ISSUE I GAVE THE STYLE IN FOOTER..

**Comment by Meetpidev** [comment]
https://github.com/Open-Code-Crafters/FitFlex/pull/450#issue-2642961432 

@AKSHITHA-CHILUKA 
 in this they assigned me to build that feature.. **just see in issue**.. but when i sent PR.. they told that they dont need it... so why they assigned me to build it ? so thats i i want to you merged it here.. so that my efforts are not lots

**Comment by AKSHITHA-CHILUKA** [comment]
> [Open-Code-Crafters/FitFlex#450 (comment)](https://github.com/Open-Code-Crafters/FitFlex/pull/450#issue-2642961432)
> 
> @AKSHITHA-CHILUKA in this they assigned me to build that feature.. **just see in issue**.. but when i sent PR.. they told that they dont need it... so why they assigned me to build it ? so thats i i want to you merged it here.. so that my efforts are not lots

level2 for this

**Pull request merged**
