### PR TITLE
Create amena-pr.md

### PR DESCRIPTION
**Pull request by Amenamirza**
Hi GSSOC team,

@sanjay-kv @MastanSayyad 

https://github.com/Amenamirza/Open-source-Practice

### CODE REVIEW

**Comment by MastanSayyad** [comment]
@Amenamirza Kindly Dont Lie I saw your profile, you have only created one PR till now and that too this one

image

**Comment by Amenamirza** [comment]
I don't know what to do I just did it as sanjay sir directed

**Comment by Amenamirza** [comment]
So please don't say that I'm telling lie

**Comment by MastanSayyad** [comment]
@Amenamirza Sanjay said to add your contributed Open PR links under gssoc projects and as per your GitHub profile, you have created only this PR till now! I said don't lie as most of the people try to spam PRs same like this to gain points, I apologize.

**Pull request closed without merging**
