### PR TITLE
Sneha.md

### PR DESCRIPTION
**Pull request by snehas-05**
My these 3 pr's have been ignored. I kindly request you too have a look on them. Thankyou!
https://github.com/Anjaliavv51/Retro/pull/805 - issue number #629
https://github.com/Devanik21/ISRO_Mining_Site_FINAL_APP/pull/100   - issue number #76
https://github.com/kabaddiPy/kabaddiPy/pull/30- issue number #26

### CODE REVIEW

**Comment by aslams2020** [comment]
@snehas-05 In the PRs above, mention the issue number you were assigned to work on

**Comment by snehas-05** [comment]
Added

**Review by aslams2020 — APPROVED** [review]

**Comment by aslams2020** [comment]
For Kabaddi Py PR - lv3 
For other two - lv2

**Comment by snehas-05** [comment]
Thankyou so much

**Pull request merged**
