### PR TITLE
Create Subhajit.pr.md

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
🟢➡️Hi GSSOC team, I am an active contributor in gssoc-ext,

There are some PR's which are merged but not given the correct level, in this same project the admin gives level 3 who added less than me but he didn't give me level 3 even though I added more...

I request you please review these 3 PR and upgrade the level 2 to 3... 
I would be very grateful if you could upgrade the levels 2 to 3.. 🙏🏻

https://github.com/vishanurag/Canvas-Editor/pull/1181#issue-2631225498

https://github.com/anuragverma108/SwapReads/pull/4295#issue-2624377639

https://github.com/mansiruhil13/Bobble-AI/pull/1172#issue-2635341528

🟢➡️There are some PRs which are yet to be merged I will add the link and respective level,

Please review and merge these PR.. 🙏🏻

level 1 

https://github.com/vishanurag/Canvas-Editor/pull/1274#issue-2646574385 

Leve 2

https://github.com/Akshat111111/NexTrade/pull/115#issue-2644027294

https://github.com/PriyaGhosal/BuddyTrail/pull/1925#issue-2636583848

https://github.com/PriyaGhosal/BuddyTrail/pull/1924#issue-2636486140

https://github.com/sakeel-103/DFS-BFS-Graph-Travers/pull/606#issue-2646470163

Level 3

https://github.com/PriyaGhosal/BuddyTrail/pull/1918#issue-2636080139

https://github.com/PriyaGhosal/BuddyTrail/pull/1927#issue-2636638307

https://github.com/sakeel-103/DFS-BFS-Graph-Travers/pull/605#issue-2646432937

🟢➡️He assigned level but forgot to merge.. Please merge these PRs... 🙏🏻

https://github.com/ankit071105/Ticket-Booking/pull/1083#issue-2642334189

https://github.com/ankit071105/Ticket-Booking/pull/1086#issue-2642382296

https://github.com/ankit071105/Ticket-Booking/pull/1087#issue-2642386707

https://github.com/ankit071105/Ticket-Booking/pull/1088#issue-2642391510

https://github.com/ankit071105/Ticket-Booking/pull/1089#issue-2642395763

Thank You 🙏🏻

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@aslams2020 @MastanSayyad @AKSHITHA-CHILUKA please help me..

**Comment by AKSHITHA-CHILUKA** [comment]
if you put all your pr's in one link its difficult to add points @Subhajit-2023-44 only keep 3 pr's in one pr

**Comment by Subhajit-2023-44** [comment]
> if you put all your pr's in one link its difficult to add points @Subhajit-2023-44 only keep 3 pr's in one pr

@AKSHITHA-CHILUKA 🙏🏻 actually don't know how to send multiple PRs at the same time 😞😞... also just 30 min left, 

please help me 



He assigned level but forgot to merge.. just merge these PRs... 👇🏻

https://github.com/ankit071105/Ticket-Booking/pull/1083#issue-2642334189

https://github.com/ankit071105/Ticket-Booking/pull/1086#issue-2642382296

https://github.com/ankit071105/Ticket-Booking/pull/1087#issue-2642386707

https://github.com/ankit071105/Ticket-Booking/pull/1088#issue-2642391510

https://github.com/ankit071105/Ticket-Booking/pull/1089#issue-2642395763


upgrade the level 2 to 3 👇🏻

https://github.com/vishanurag/Canvas-Editor/pull/1181#issue-2631225498

https://github.com/anuragverma108/SwapReads/pull/4295#issue-2624377639

https://github.com/mansiruhil13/Bobble-AI/pull/1172#issue-2635341528


Please review and merge these PR..👇🏻



level 1 

https://github.com/vishanurag/Canvas-Editor/pull/1274#issue-2646574385 

Leve 2

https://github.com/Akshat111111/NexTrade/pull/115#issue-2644027294

https://github.com/PriyaGhosal/BuddyTrail/pull/1925#issue-2636583848

https://github.com/PriyaGhosal/BuddyTrail/pull/1924#issue-2636486140

https://github.com/sakeel-103/DFS-BFS-Graph-Travers/pull/606#issue-2646470163

Level 3

https://github.com/PriyaGhosal/BuddyTrail/pull/1918#issue-2636080139

https://github.com/PriyaGhosal/BuddyTrail/pull/1927#issue-2636638307

https://github.com/sakeel-103/DFS-BFS-Graph-Travers/pull/605#issue-2646432937

**Comment by AKSHITHA-CHILUKA** [comment]
https://github.com/ankit071105/Ticket-Booking/pull/1083#issue-2642334189

https://github.com/ankit071105/Ticket-Booking/pull/1086#issue-2642382296

https://github.com/ankit071105/Ticket-Booking/pull/1087#issue-2642386707

https://github.com/ankit071105/Ticket-Booking/pull/1088#issue-2642391510

https://github.com/ankit071105/Ticket-Booking/pull/1089#issue-2642395763  all level 1 so 50 points

**Comment by AKSHITHA-CHILUKA** [comment]
https://github.com/vishanurag/Canvas-Editor/pull/1181#issue-2631225498

https://github.com/anuragverma108/SwapReads/pull/4295#issue-2624377639

https://github.com/mansiruhil13/Bobble-AI/pull/1172#issue-2635341528 3 level 2 so 25*3 = 75

**Comment by AKSHITHA-CHILUKA** [comment]
if you mention remaining pr in another pr i will merge them and add labels

**Review by AKSHITHA-CHILUKA — APPROVED** [review]

**Comment by Subhajit-2023-44** [comment]
> [ankit071105/Ticket-Booking#1083 (comment)](https://github.com/ankit071105/Ticket-Booking/pull/1083#issue-2642334189)
> 
> [ankit071105/Ticket-Booking#1086 (comment)](https://github.com/ankit071105/Ticket-Booking/pull/1086#issue-2642382296)
> 
> [ankit071105/Ticket-Booking#1087 (comment)](https://github.com/ankit071105/Ticket-Booking/pull/1087#issue-2642386707)
> 
> [ankit071105/Ticket-Booking#1088 (comment)](https://github.com/ankit071105/Ticket-Booking/pull/1088#issue-2642391510)
> 
> [ankit071105/Ticket-Booking#1089 (comment)](https://github.com/ankit071105/Ticket-Booking/pull/1089#issue-2642395763) all level 1 so 50 points

merge this

**Comment by AKSHITHA-CHILUKA** [comment]
open a new pr like this and mention your pr's

**Pull request merged**
