### PR TITLE
create nirajpr.md

### PR DESCRIPTION
**Pull request by Niraj1608**
Hi GSSOC 2024 extd team this is the pr i have raised and it's not been merged. Its Level 2 PR could you review and merge it.

the PA told me its not relate to the project 
but The ATS Resume Expert is a tool built using Gemini AI too, 
This feature directly integrates with the Virtual Assistant with Gemini AI project.
https://github.com/suryanshsk/Python-Voice-Assistant-Suryanshsk/pull/554

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
This PR has been closed by the Project admin

**Comment by aslams2020** [comment]
Discuss with the PA. as he is active it depends on him to review and merge it

**Comment by Niraj1608** [comment]
@aslams2020 but he was not active from 2 days also he assign to me that issue 
https://github.com/suryanshsk/Python-Voice-Assistant-Suryanshsk/issues/440
check the issue now he is saying its not relate to the project is it a valid reason

**Comment by Niraj1608** [comment]
thank you @MastanSayyad

**Pull request merged**
