### PR TITLE
Create archit-pr.md

### PR DESCRIPTION
**Pull request by ArchitSr313**
Hi, I am **GSSOC'24 Extended Contributor**,
This is the PR i have raised and its not been merged. Could You review and merge it.
 @sanjay-kv @MastanSayyad 

https://github.com/Code-Social/official-website/pull/435

### CODE REVIEW

**Comment by AKSHITHA-CHILUKA** [comment]
Give pr link not the repo link @ArchitSr313

**Comment by ArchitSr313** [comment]
> Give pr link not the repo link @ArchitSr313

Updated

**Comment by aslams2020** [comment]
That is your forked repo link. Not the PR link

Provide valid PR link

**Comment by aslams2020** [comment]
Create a newPR

**Pull request closed without merging**
