### PR TITLE
update README.md

### PR DESCRIPTION
**Pull request by pinakviramgama**
Dear sir @sanjay-kv , i have updated readme.md with my name

please approve this pull request

### CODE REVIEW

**Comment by pinakviramgama** [comment]
Dear @sanjay-kv , please merge this pull request

**Comment by pinakviramgama** [comment]
Dear @AKSHITHA-CHILUKA , please merge this pull request

**Comment by pinakviramgama** [comment]
Dear @aslams2020 ,please merge this pull request

**Review by AKSHITHA-CHILUKA — CHANGES_REQUESTED** [review]
Please open a new pr as I can see you have changed many lines in the document

**Comment by AKSHITHA-CHILUKA** [comment]
Open a new pr I will merge it soon

**Pull request closed without merging**
