### PR TITLE
Create Siddhi-PR.md

### PR DESCRIPTION
**Pull request by Siddhisony**
Hi GSSOC team,
https://github.com/Siddhisony/READMEasy/tree/emojiandgif , this is the PR which has been assigned to me and it is not merged yet. It is a level 2 PR. Could you please review it? I am open to any kind of improvements.

Thank you!

### CODE REVIEW

**Comment by aslams2020** [comment]
that is not a PR link. add valid link

**Comment by aslams2020** [comment]
give proper link asap

**Comment by Siddhisony** [comment]
> that is not a PR link. add valid link

https://github.com/Siddhisony/READMEasy.git

**Comment by Siddhisony** [comment]
> give proper link asap

https://github.com/BamaCharanChhandogi/READMEasy/pull/129

**Comment by Siddhisony** [comment]
Do I have to change anything?

**Comment by AKSHITHA-CHILUKA** [comment]
no labels will be assigned for this @Siddhisony

**Comment by Siddhisony** [comment]
I understand that it's a lot to merge or close the requests. May I know the reason why I haven't got assigned any labels?

**Comment by aslams2020** [comment]
Because, you didn't provide the correct link before 7pm

**Pull request closed without merging**
