### PR TITLE
 sneha1.md

### PR DESCRIPTION
**Pull request by snehas-05**
I would request you to kindly consider these pr's also.
https://github.com/Akshat111111/NexTrade/pull/39 -- issue number #25
https://github.com/Harshdev098/Research-Nexas/pull/196 -- issue number #185
https://github.com/Devasy23/FaceRec/pull/91 --issue number #87

### CODE REVIEW

**Comment by AKSHITHA-CHILUKA** [comment]
https://github.com/Akshat111111/NexTrade/pull/39 for this pr the PA requested for a change so please do it
https://github.com/Harshdev098/Research-Nexas/pull/196 asked for some changes so please do it
https://github.com/Devasy23/FaceRec/pull/91 here the PA said it is not needed so can't assign you points @snehas-05

**Comment by snehas-05** [comment]
@AKSHITHA-CHILUKA 
I have made all the changes required which the PA told me. https://github.com/Harshdev098/Research-Nexas/pull/196

**Comment by snehas-05** [comment]
https://github.com/Devasy23/FaceRec/pull/91 --issue number #87 
And for this pr the owner said he will review and revert me back but you're saying the PA said this pr is not needed. I don't think he meant this. I have added the screenshot below.[Screenshot_2024-11-10-09-29-59-41_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/user-attachments/assets/06557b60-94c0-453b-9569-91b626474697)

**Comment by AKSHITHA-CHILUKA** [comment]
> @AKSHITHA-CHILUKA I have made all the changes required which the PA told me. [Harshdev098/Research-Nexas#196](https://github.com/Harshdev098/Research-Nexas/pull/196)

image

**Comment by AKSHITHA-CHILUKA** [comment]
> [Devasy23/FaceRec#91](https://github.com/Devasy23/FaceRec/pull/91) --issue number #87 And for this pr the owner said he will review and revert me back but you're saying the PA said this pr is not needed. I don't think he meant this. I have added the screenshot below.[Screenshot_2024-11-10-09-29-59-41_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/user-attachments/assets/06557b60-94c0-453b-9569-91b626474697)

image

**Comment by snehas-05** [comment]
> > @AKSHITHA-CHILUKA I have made all the changes required which the PA told me. [Harshdev098/Research-Nexas#196](https://github.com/Harshdev098/Research-Nexas/pull/196)
> 
> image
> 



Commited changes you can see

**Comment by snehas-05** [comment]
@AKSHITHA-CHILUKA ?

**Pull request closed without merging**
