### PR TITLE
 shriyadindi-upr

### PR DESCRIPTION
**Pull request by shriyadindi**
Unmerged PR

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
these all are issues and not PRs

**Comment by shriyadindi** [comment]
They are the PRs, just open the link

**Comment by aslams2020** [comment]
i can see your other PRs separately in this repo..

clear me if those contains this ?

**Comment by aslams2020** [comment]
i will review them now i think you created many separate

**Comment by shriyadindi** [comment]
I've first created a single repo containing all the PRs but then many of them have created a separate pr for each unmerged pr so I thought that is the way and i created them separately

**Comment by aslams2020** [comment]
yeah its fine

**Comment by aslams2020** [comment]
will review them

**Comment by shriyadindi** [comment]
@aslams2020 okay

**Pull request closed without merging**
