### PR TITLE
Create sachinsingh-pr.md

### PR DESCRIPTION
**Pull request by sachinggsingh**
Hi GSsoc Team
I am Sachin here are the link of my PR's which are level 1 has not been merged Could You review them and merge them

@sanjay-kv  @MastanSayyad 
https://github.com/PriyaGhosal/BuddyTrail/pull/1967 https://github.com/PriyaGhosal/BuddyTrail/pull/1968 https://github.com/PriyaGhosal/BuddyTrail/pull/1969 https://github.com/strivedi4u/hacktoberfest24_projects/pull/48 https://github.com/SavindiNawoda/CalculatorApp-Hacktoberfest2024/pull/6

### CODE REVIEW

**Review by aslams2020 — COMMENTED** [review]
We can not merge the PRs assigned by the github bot recently..Unless the projectadmin responds to either issue or PR itself.

the other two PR namely -
https://github.com/strivedi4u/hacktoberfest24_projects/pull/48 https://github.com/SavindiNawoda/CalculatorApp-Hacktoberfest2024/pull/6
are not a part of GSSoC extended.

**Comment by aslams2020** [comment]
According

**Comment by sachinggsingh** [comment]
> We can not merge the PRs assigned by the github bot recently..Unless the projectadmin responds to either issue or PR itself.
> 
> the other two PR namely - [strivedi4u/hacktoberfest24_projects#48](https://github.com/strivedi4u/hacktoberfest24_projects/pull/48) [SavindiNawoda/CalculatorApp-Hacktoberfest2024#6](https://github.com/SavindiNawoda/CalculatorApp-Hacktoberfest2024/pull/6) are not a part of GSSoC extended.

And if they are not Accepted by the reviewer till tomorrow then they wont be counted?????

**Comment by MastanSayyad** [comment]
@sachinggsingh Yes! The issue and PR both are created 8 hours back, without any conversation with the PA, tag the PA their and of they permit and merge then only you will get points, I have announced about this on the discord contributor announcements, kindly check

**Pull request closed without merging**
