### PR TITLE
Create Subhajit.md

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
🟢➡️There are some PRs which are yet to be merged I will add the link and respective level,

Please review and merge these PR.. 🙏🏻

level 1

https://github.com/vishanurag/Canvas-Editor/pull/1274#issue-2646574385

Leve 2

https://github.com/Akshat111111/NexTrade/pull/115#issue-2644027294

https://github.com/PriyaGhosal/BuddyTrail/pull/1925#issue-2636583848

https://github.com/PriyaGhosal/BuddyTrail/pull/1924#issue-2636486140

https://github.com/sakeel-103/DFS-BFS-Graph-Travers/pull/606#issue-2646470163

Level 3

https://github.com/PriyaGhosal/BuddyTrail/pull/1918#issue-2636080139

https://github.com/PriyaGhosal/BuddyTrail/pull/1927#issue-2636638307

https://github.com/sakeel-103/DFS-BFS-Graph-Travers/pull/605#issue-2646432937

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@AKSHITHA-CHILUKA

**Comment by AKSHITHA-CHILUKA** [comment]
https://github.com/Akshat111111/NexTrade/pull/115#issue-2644027294

https://github.com/PriyaGhosal/BuddyTrail/pull/1925#issue-2636583848 level 1 and level2

**Comment by Subhajit-2023-44** [comment]
please merge with 123 levels then i will open another pr

**Comment by AKSHITHA-CHILUKA** [comment]
https://github.com/PriyaGhosal/BuddyTrail/pull/1924#issue-2636486140 level 1 

https://github.com/sakeel-103/DFS-BFS-Graph-Travers/pull/606#issue-2646470163 no  level

**Comment by Subhajit-2023-44** [comment]
please merge then i will open a new pr for this 

https://github.com/ankit071105/Ticket-Booking/pull/1083#issue-2642334189

https://github.com/ankit071105/Ticket-Booking/pull/1086#issue-2642382296

https://github.com/ankit071105/Ticket-Booking/pull/1087#issue-2642386707

https://github.com/ankit071105/Ticket-Booking/pull/1088#issue-2642391510

https://github.com/ankit071105/Ticket-Booking/pull/1089#issue-2642395763 all level 1 so 50 points

**Comment by AKSHITHA-CHILUKA** [comment]
https://github.com/PriyaGhosal/BuddyTrail/pull/1918#issue-2636080139

https://github.com/PriyaGhosal/BuddyTrail/pull/1927#issue-2636638307

https://github.com/sakeel-103/DFS-BFS-Graph-Travers/pull/605#issue-2646432937 are level 2

**Comment by AKSHITHA-CHILUKA** [comment]
I have given 80 points

**Pull request merged**
