### PR TITLE
Create Khushi Dua.md

### PR DESCRIPTION
**Pull request by Khushi-Dua**
Pending PR's

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
All the PRs are closed by the Project admin for some reasons. 
This PRs Cannot be reviewed further.

**Comment by Khushi-Dua** [comment]
What about this  this is open , not being reviewed by Project admin or maintainers, which is mentioned as 1st one in my file Khushi Dua.md
here is my pending PR: NO one reviewed this
https://github.com/Ramsey99/fest-registration/pull/80

**Comment by aslams2020** [comment]
That does not comes under GSSoC extended

**Comment by Khushi-Dua** [comment]
What about this this is open , not being reviewed by Project admin or
maintainers, which is mentioned as 1st one in my file Khushi Dua.md
here is my pending PR: NO one reviewed this
Ramsey99/fest-registration#80
<https://github.com/Ramsey99/fest-registration/pull/80>

**Comment by aslams2020** [comment]
That project is not under gssoc extended

**Pull request closed without merging**
