### PR TITLE
create rutika pr.md

### PR DESCRIPTION
**Pull request by rutikakengal**
Hi GSSOC Team!
I raised the PR but is not has been merged
Could you review and merge it 
@sanjay-kv @MastanSayyad 
Please review it 
https://github.com/dohinaf/basic-icecream-website/pull/839

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
1. https://github.com/vishal02527/My-Strength-Shree-Krishna/pull/646/
This PR has No code changes -- cant be reviewed

2. https://github.com/dohinaf/basic-icecream-website/pull/839
This is a latest PR just 25mins ago, If it stays unmerged till tomorrow afternoon, then only create a PR

3. https://github.com/vishal02527/My-Strength-Shree-Krishna/pull/669
This has been already merged by mastan with level3, 4hrs ago -- why repeat.

**Comment by aslams2020** [comment]
This PR cannot be merged.

**Comment by rutikakengal** [comment]
they assign me yesterday , ontomorrow onwards it can be merge ? thats why I create PR @aslams2020

**Comment by rutikakengal** [comment]
As tomorrow is last day , and I create issue since 1 week ago but they assign me yesterday then i create PR to there repo and here also , They assign me 2 issue and I done it . they also not responding @aslams2020

**Comment by aslams2020** [comment]
@rutikakengal Wait till tomorrow afternoon..because they may respond to it 

If not, then you can create PR tomorrow -- we will review it. Currently the priority is the ones whos PRs are unmerged for so many days

**Comment by aslams2020** [comment]
Tomorrow before 7pm -- is the deadline.

**Comment by rutikakengal** [comment]
Ok but please they not respond then you review it and merge it @aslams2020

**Comment by aslams2020** [comment]
Yeah, we will merge it for sure.

**Pull request closed without merging**
