### PR TITLE
create rutikakengal pr.md

### PR DESCRIPTION
**Pull request by rutikakengal**
Hi GSSOC Team!
This PR I created but it not been reviewd and merged 

Could you please review and merge it 

Please review and add labels to it as PA adding only gssoc label,
@sanjay-kv @MastanSayyad 

https://github.com/dohinaf/basic-icecream-website/pull/840

### CODE REVIEW

**Comment by AKSHITHA-CHILUKA** [comment]
This repo is not under gssoc-ext

**Review by aslams2020 — CHANGES_REQUESTED** [review]
https://github.com/dohinaf/basic-icecream-website/pull/840

The other 3 PRs i just closed stating the reason. 
The one you added just now, is just 7mins ago ++ (IT IS NOT ASSIGNED TO YOU)

**Comment by aslams2020** [comment]
Please dont repeat same

**Comment by rutikakengal** [comment]
It is assigned to me, then I start work on it  and gssoc label also added .  @AKSHITHA-CHILUKA @aslams2020 
Screenshot 2024-11-09 202315

**Comment by aslams2020** [comment]
The labels have been added using some workflow. you were not assigned by the PA to work on it

**Comment by aslams2020** [comment]
image

**Pull request closed without merging**
