### PR TITLE
New pull request for update README.md

### PR DESCRIPTION
**Pull request by pinakviramgama**
Dear @AKSHITHA-CHILUKA i have made new pr, please merge.

### CODE REVIEW

**Comment by pinakviramgama** [comment]
Dear @AKSHITHA-CHILUKA , i have created new pull request, please merge it.

**Comment by AKSHITHA-CHILUKA** [comment]
Just add at the details , once see all the changes you have done

**Comment by pinakviramgama** [comment]
mam, can i resolve conflicts ?

**Comment by pinakviramgama** [comment]
Dear @AKSHITHA-CHILUKA , conflicts are resolved, please merge this pull req.

**Comment by pinakviramgama** [comment]
Dear @AKSHITHA-CHILUKA , please merge this pull request

**Review by AKSHITHA-CHILUKA — APPROVED** [review]

**Comment by pinakviramgama** [comment]
Thanks @AKSHITHA-CHILUKA , for accepting this pull req.

**Pull request merged**
