### PR TITLE
unmerged pr

### PR DESCRIPTION
**Pull request by Palmistry2310**
https://github.com/GarimaSingh0109/Resum-Resume/pull/1013/

level-3

@AKSHITHA-CHILUKA 
@aslams2020

### CODE REVIEW

**Comment by Palmistry2310** [comment]
@AKSHITHA-CHILUKA labels are left to add

**Comment by AKSHITHA-CHILUKA** [comment]
garima will merge them if you resolve the conflict

**Comment by Palmistry2310** [comment]
@AKSHITHA-CHILUKA i have already resolved the conflicts

**Comment by Palmistry2310** [comment]
@sneha056 i have already resolved conflicts , please see to it

**Comment by aslams2020** [comment]
Done

**Comment by aslams2020** [comment]
the time is up.

**Pull request merged**
