### PR TITLE
Create kaiyumdev.md

### PR DESCRIPTION
**Pull request by kaioumdev**
Hi GSSOC Team ! 
This is the PR I have raised and working on two issues one have merged but not add any levels another one not merge. Could you review and Merge it please?

https://github.com/beRajeevKumar/Front

### CODE REVIEW

**Comment by MastanSayyad** [comment]
@kaiyumdev give valid PR Link

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Both of them are still not the valid PRs @kaiyumdev 

Just click and open the unmerged PR of yours and Copy the Url and submit it here

**Review by aslams2020 — CHANGES_REQUESTED** [review]
These links are for issues
also, you are not assigned to them -- so no points for these

**Comment by kaioumdev** [comment]
I apologize for the confusion regarding my previous pull requests. I understand now that they weren't submitted correctly.

I've opened the unmerged pull requests as per your instructions and copied the URLs below for submission. I also realize that I wasn’t assigned to those issues initially, so I understand why points weren't awarded.

Thank you for your guidance @aslams2020, and I appreciate your patience as I work to resolve this.

**Pull request closed without merging**
