### PR TITLE
Create pal.md

### PR DESCRIPTION
**Pull request by Palmistry2310**
hello GSSOC Team!
These are few unmerged prs.
level-3
 https://github.com/GarimaSingh0109/Resum-Resume/pull/820
level-3
 https://github.com/GarimaSingh0109/Resum-Resume/pull/1012
level-2
 https://github.com/GarimaSingh0109/Resum-Resume/pull/1013
level-2
 https://github.com/GarimaSingh0109/Resum-Resume/pull/1014

about pr 820:
in this mentor suggested some changes , to change color accordding to the color pallete in readme file, i tried to ask her out to elaborate change as no pallete is mentioned in readme file but yet there is no response.
i created the whole new page, i dont want my efforts to go in vain. please look after it.

### CODE REVIEW

**Comment by Palmistry2310** [comment]
do i need to create separate prs here for different prs? @AKSHITHA-CHILUKA

**Comment by AKSHITHA-CHILUKA** [comment]
yes create separate pr's

**Comment by GarimaSingh0109** [comment]
@Palmistry2310 you have not resolved conflicts you need to resolve conflicts to get points
1013 and 1014

**Comment by AKSHITHA-CHILUKA** [comment]
@Palmistry2310 Yes you have to resolve the changes mentioned by the PA then she will merge it

**Pull request closed without merging**
