### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by trahulprabhu38**
Added my name and made the names on under the T list appear in an order .please review the changes.
@sanjay-kv @HimangshuSharma01 review and merge

### CODE REVIEW

**Review by HimangshuSharma01 — COMMENTED** [review]
Hi, Thanks for contributing to this repo.
If you would like to contribute more and learn. Join my github org https://github.com/recodehive

Playlist on YouTube Watch to learn more about how you can earn badge and free GitHub Pro.
GitHub Tutorials

Now if you want to have a free github profile review: Check this out: https://topmate.io/sanjaykv/1135910/pay
Thanks,
behalf of (Sanjay Viswanathan)

**Review by MastanSayyad — COMMENTED** [review]
@HimangshuSharma01 please don't add such High labels for such PRs. Remove levels, the changes are one liner.

**Comment by HimangshuSharma01** [comment]
> @HimangshuSharma01 please don't add such High labels for such PRs. Remove levels, the changes are one liner. 

Hey I was asked to do so by Sanjay sir

**Comment by HimangshuSharma01** [comment]
> @HimangshuSharma01 please don't add such High labels for such PRs. Remove levels, the changes are one liner. 

Okay I'm doing it for everyone just give me some time

**Pull request merged**
