### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mahaveergurjar**
Added my name.

### CODE REVIEW

**Review by HimangshuSharma01 — COMMENTED** [review]
Hi, Thanks for contributing to this repo.
If you would like to contribute more and learn. Join my github org https://github.com/recodehive

Playlist on YouTube Watch to learn more about how you can earn badge and free GitHub Pro.
[GitHub Tutorials](https://stream.recodehive.com/github)

Now if you want to have a free github profile review: Check this out: https://topmate.io/sanjaykv/1135910/pay
Thanks,
behalf of (Sanjay Viswanathan)

**Comment by aslams2020** [comment]
@mahaveergurjar Please create a New PR, you have removed many entries in this PR.

image

**Comment by mahaveergurjar** [comment]
Okay please reopen i will update the pr

**Comment by aslams2020** [comment]
@mahaveergurjar It'll create conflicts. please create a new One.

**Pull request closed without merging**
