### PR TITLE
Create rajnil-pr.md

### PR DESCRIPTION
**Pull request by rajnil9**
HI GSSOC team this is my PR which is still not merged .  Please Look into it .

@sanjay-kv @aslams2020 

https://github.com/iamrahulmahato/master-web-development/pull/2311

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
@rajnil9 You were not assigned to work on it. This PR cannot be merged

**Comment by rajnil9** [comment]
@aslams2020  so i can't use it here until it has been assigned to me . Alright . Well this maintainers generally assign them at the end only . I cant do anything now if he doesn't come online .

**Comment by aslams2020** [comment]
@rajnil9 Still, according to guidelines -- Contributor should not start working on an issue until gets assigned.

**Comment by rajnil9** [comment]
@aslams2020 alright , will wait then . What more can I do apart from that

**Pull request closed without merging**
