### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by trinetra110**
Added my name

### CODE REVIEW

**Review by HimangshuSharma01 — COMMENTED** [review]
Hi, Thanks for contributing to this repo.
If you would like to contribute more and learn. Join my github org https://github.com/recodehive

Playlist on YouTube Watch to learn more about how you can earn badge and free GitHub Pro.
[GitHub Tutorials](https://stream.recodehive.com/github)

Now if you want to have a free github profile review: Check this out: https://topmate.io/sanjaykv/1135910/pay
Thanks,
behalf of (Sanjay Viswanathan)

**Review by RadhikaMalpani1702 — COMMENTED** [review]
@mastansayyad can you review this PR?

**Comment by HimangshuSharma01** [comment]
> @mastansayyad can you review this PR?

@RadhikaMalpani1702 
Hey Radhika,
I hope you are doing well I would be grateful if you can help me please see my message on LinkedIn, I just had some questions regarding hacktoberfest.

**Review by MastanSayyad — COMMENTED** [review]
image

Hi @HimangshuSharma01 He just added his name and a github link in a list + these are minimal readme changes, therefore this will have No levels

Please remove the level labels. thank you!

**Comment by HimangshuSharma01** [comment]
> image
> 
> Hi @HimangshuSharma01 He just added his name and a github link in a list + these are minimal readme changes, therefore this will have No levels
> 
> Please remove the level labels. thank you!

Hey @MastanSayyad I am waiting for the reply of Sanjay sir as he is the admin as soon as he allows I will proceed on doing this

**Pull request merged**
