### PR TITLE
Added my name to README.md

### PR DESCRIPTION
**Pull request by shuvojitss**
Added my name.

### CODE REVIEW

**Review by HimangshuSharma01 — COMMENTED** [review]
Hi, Thanks for contributing to this repo.
If you would like to contribute more and learn. Join my github org https://github.com/recodehive

Playlist on YouTube Watch to learn more about how you can earn badge and free GitHub Pro.
[GitHub Tutorials](https://stream.recodehive.com/github)

Now if you want to have a free github profile review: Check this out: https://topmate.io/sanjaykv/1135910/pay
Thanks,
behalf of (Sanjay Viswanathan)

**Comment by shuvojitss** [comment]
@HimangshuSharma01 Why the levels and points have been removed. ??

**Comment by shuvojitss** [comment]
@HimangshuSharma01 please add the gssoc and level labels.🙏🙏

**Comment by HimangshuSharma01** [comment]
> @HimangshuSharma01 please add the gssoc and level labels.🙏🙏

The changes that were made are only of one line I was asked to remove it

**Comment by shuvojitss** [comment]
@HimangshuSharma02 what should I do now please help. My points haw been reduced. Please add the level and gssoc ext. To the pull request.🙏🙏🙏

**Pull request merged**
