### PR TITLE
Create Sanchit.md

### PR DESCRIPTION
**Pull request by sanchitc05**
Added my unmerged pr's

### CODE REVIEW

**Comment by AKSHITHA-CHILUKA** [comment]
@MastanSayyad Will look into it as you have more pr's

**Comment by sanchitc05** [comment]
@AKSHITHA-CHILUKA Okay

**Review by MastanSayyad — APPROVED** [review]
Merged and added points

**Comment by MastanSayyad** [comment]
@sanchitc05 I have merged your other PRs and added labels for those that I didn't have access!

**Comment by sanchitc05** [comment]
@MastanSayyad thank you so much 😊

**Comment by sanchitc05** [comment]
Hii @MastanSayyad I got some more unmerged pr's should I create another pr or just add them in the comment here?

**Comment by AKSHITHA-CHILUKA** [comment]
create another pr @sanchitc05

**Comment by sanchitc05** [comment]
Alright @AKSHITHA-CHILUKA thanks for replying.

**Comment by sanchitc05** [comment]
I created a new pr as you said @AKSHITHA-CHILUKA, please look into it.
Thank You.

**Pull request merged**
