### PR TITLE
Added the name & github link

### PR DESCRIPTION
**Pull request by SaiSruthisri**
Added my name & my github link

### CODE REVIEW

**Review by AKSHITHA-CHILUKA — APPROVED** [review]

**Comment by SaiSruthisri** [comment]
Hi @AKSHITHA-CHILUKA you have assigned me , I have a doubt can you please clarify .  Now i just have to make changes in readme , better it & raise a pr, is that it .

**Comment by AKSHITHA-CHILUKA** [comment]
@SaiSruthisri 
you have already made the changes 
image

**Comment by SaiSruthisri** [comment]
understood , do i get points for this , since you've added level2 label

**Comment by AKSHITHA-CHILUKA** [comment]
@SaiSruthisri  yes you will get points .

**Comment by SaiSruthisri** [comment]
ok thank you!!

**Pull request merged**
