### PR TITLE
Create Dimpal-Pr.md

### PR DESCRIPTION
**Pull request by Dimpalpatil**
hi GSSOC team this is the PR i have raised and its not been merged. its a level 1 PR
colud you review and merged it.
https://github.com/Dimpalpatil/Open-source-Practice
@sanjay-kv @MastanSayyad

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
That is not a valid PR link.

If you have unmerged PRs, create a .md file and add PR links to it.

**Comment by aslams2020** [comment]
No response. If you have any Unmerged PRs -- create a new PR

**Comment by Dimpalpatil** [comment]
I have done with PR

**Comment by Dimpalpatil** [comment]
Can check mail id ***@***.***

**Pull request closed without merging**
