### PR TITLE
Create Subhajit-2023-44.pr.md

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
There are some PRs which are yet to be merged I will add the link and respective level(assigned by admin), 

Please review and merge these 3 PR's with these labels..

labels assigned by admin:

image

PR link :
https://github.com/beRajeevKumar/Frontend_Mentor/pull/297#issue-2583009584

labels assigned by admin:
image

PR link :
https://github.com/Anjaliavv51/Retro/pull/810#issue-2630951151

labels assigned by admin:
image

PR link :
https://github.com/Vin205/Enyanjyoti/pull/558#issue-2631059109

Thank You

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@AKSHITHA-CHILUKA @aslams2020

**Comment by Subhajit-2023-44** [comment]
@aslams2020 @AKSHITHA-CHILUKA Please review and merge these 3 PR's with these labels..

**Comment by aslams2020** [comment]
for fix alignment - lv1
for visitor count - it cant be a level3, it is a level2
for feedback form - it is a level2

**Comment by Subhajit-2023-44** [comment]
> for fix alignment - lv1 for visitor count - it cant be a level3, it is a level2 for feedback form - it is a level2

okay sir, Thank You

**Pull request merged**
