### PR TITLE
My pending PRs

### PR DESCRIPTION
**Pull request by ygowthamr**
My pending PRs pls merge it.

@sanjay-kv @MastanSayyad @aslams2020

### CODE REVIEW

**Comment by AKSHITHA-CHILUKA** [comment]
Please provide the links to your pr @ygowthamr

**Comment by AKSHITHA-CHILUKA** [comment]
https://github.com/DharshiBalasubramaniyam/ice-cream-parlour-website/pull/1108
https://github.com/DharshiBalasubramaniyam/ice-cream-parlour-website/pull/1107
so basic change can't add points for these 2

https://github.com/ankit071105/Ticket-Booking/pull/1093 - level1 
https://github.com/tanishaness/SPROCTOR/pull/48 - as closed by the PA no points

**Comment by ygowthamr** [comment]
https://github.com/tanishaness/SPROCTOR/pull/48 - This is closed abruptly without give giving me levels. 
I should get points for what i have did right?
@AKSHITHA-CHILUKA

**Comment by ygowthamr** [comment]
@AKSHITHA-CHILUKA Pls check that issue which i am facing issue with mentioned PA.

**Comment by ygowthamr** [comment]
@AKSHITHA-CHILUKA 
 She given me level but closed pls look into it.
 - image

**Comment by AKSHITHA-CHILUKA** [comment]
screencapture-github-tanishaness-SPROCTOR-pull-48-files-2024-11-09-18_33_55
for this minimal change level3 cannot be given

**Comment by ygowthamr** [comment]
@AKSHITHA-CHILUKA Give me some level, atleast level1

**Comment by AKSHITHA-CHILUKA** [comment]
No as you are in top 50 we expect more from you so for minimal change you cannot get level 1

**Comment by MastanSayyad** [comment]
I have balanced your scores @ygowthamr, this was closed by the PA as it was a workflow PR, and this PR already has a level 1 label. Your other PRs have been merged, and you have received points for those on the respective PRs.

**Comment by ygowthamr** [comment]
@MastanSayyad Thank you

**Comment by ygowthamr** [comment]
@MastanSayyad @aslams2020 
My another PR Link: 
 - https://github.com/PriyaGhosal/BuddyTrail/pull/2001
 
 Pls add level and merge it.

**Comment by ygowthamr** [comment]
@AKSHITHA-CHILUKA @MastanSayyad @aslams2020 Pls check and merge my pending PR 
PR link : https://github.com/PriyaGhosal/BuddyTrail/pull/2001
I also added another PR and added the above link

**Comment by AKSHITHA-CHILUKA** [comment]
image
 cannot add level labels for this

**Comment by ygowthamr** [comment]
@AKSHITHA-CHILUKA Code may be small but it is helpful feature. I implemented same alike changes in other repos they have given me levels.

**Pull request merged**
